### ISSUE TITLE
Make ignoring of readonly fields an option

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/jquery-validation#1300]
As reported in https://github.com/jzaefferer/jquery-validation/pull/1261#issuecomment-59397104, always ignoring readonly fields is not a good idea (and shouldn't have landed in a patch release).

From the comment:

> I upgraded to 1.13.1 and this broke my form as a user is now able to submit a form when readonly field is invalid. Is there any way we can make this an option instead? Sometimes the practice on a mobile website is to render a field readonly so that the keyboard isn't shown, the user is then given an alternative method of input, e.g., datepicker. 

I think a good solution for this would be to move the `[readonly]` selector to the ignore option's default value, while leaving the other `not` selectors as-is. @bootsycollins would that work for you?

**Comment by jamespratt** [comment]
@jzaefferer, I also agree #1261 was a bad idea but disagree with adding readonly to the ignore options by default.  It is common practice to use a readonly field as the backing field for an alternative input method, such as a date picker, slider, etc.

![image](https://cloud.githubusercontent.com/assets/2071764/5925486/714b3ec2-a629-11e4-9596-2449c389a45a.png)

Since readonly fields are always passed to the form processor, making them functionally different than a disabled field in the HTML spec, I think they should remain validated by default and that the best scenario is a revert of #1261.

**Comment by jzaefferer** [comment]
@jamespratt I think you're right, better to revert and document when and how to add `[readonly]` to the ignore option. Could you put together a PR for the revert and maybe even one for better [docs](https://github.com/jzaefferer/validation-content)?
