### ISSUE TITLE
rule('add') for an element overwriting rules for all previous elements

### ISSUE THREAD

**Issue by soho737** [jzaefferer/jquery-validation#1385]
See: http://jsfiddle.net/1zmyof1a/

If i dynamically add rules like this:

$("#someForm").validate();
$("#someInput").rules("add", {minlength: 4});
$("#anotherInput").rules("add", {minlength: 8});

then the rule for someInput will be overwritten with the rule for "anotherInput".

I preprared a little example in jsFiddle

**Comment by wozzo** [comment]
http://jsfiddle.net/bLr630ef/1/

It seems each call to rules is overwriting other elements that aren't matched. 

$("#someForm").validate();
$("#someInput").rules("add", {minlength: 4});

Will still leave the other input with the new rule and clears it of any previously defined rules.

**Comment by jzaefferer** [comment]
Thanks for the report. The problem is a lack of name attributes on both your fiddles. Adding names to the inputs [fixed the issue](http://jsfiddle.net/xeb48zst/). Missing name attributes also cause other issues, and while the error handling could be better, for now the name attribute will stay as required.
