### ISSUE TITLE
email validation is not working proper

### ISSUE THREAD

**Issue by afuzail** [jzaefferer/jquery-validation#1598]
I mean when we type 'fuzail1280@gmail.com.com' it is invalid value, but it is showing valid.

**Comment by FagnerMartinsBrack** [comment]
See [here](https://github.com/jzaefferer/jquery-validation/tree/6936d3c833c50aba22817e806bff74053acbd352#reporting-issues-and-contributing-code)

**Comment by staabm** [comment]
See https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md

> IMPORTANT NOTE ABOUT EMAIL VALIDATION. As of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use. We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.

see https://github.com/jzaefferer/validation-content/pull/14/files for how to use a custom email pattern

**Comment by cwallacetlc** [comment]
On Fri, 02 Oct 2015 03:49:17 -0700
Fuzail Ahmed <notifications@github.com> wrote:

> I mean when we type 'fuzail1280@gmail.com.com' it is invalid value,
> but it is showing valid.

That is a valid form for an email address.  

What you are looking for is an MX check, which queries DNS for the
domain name "gmail.com.com" and looks for an MX record.  I'm pretty
sure that doesn't exist in the jquery validator.  You'll have to either
implement it yourself, or find another module that does it.

If you have a Perl backend, you can use the Email::Valid perl module to
do an MX check.

...and, it turns out gmail.com.com is a valid MX after all! :-/

-- 

C. Chad Wallace, B.Sc.
The Lodging Company
http://www.lodgingcompany.com/
OpenPGP Public Key ID: 0x262208A0

**Comment by afuzail** [comment]
thank you very much sir.
and i am sorry for wrong question.

afterall this plugin is outstanding.

and i am sorry again sir
