### ISSUE TITLE
Error hidden, but input error class not removed

### ISSUE THREAD

**Issue by danielocdh** [jzaefferer/jquery-validation#1632]
https://jsfiddle.net/p9m1u8ry/

Any easy way to fix it?

Thanks

**Comment by staabm** [comment]
@danielocdh I can see what you mean but I am not sure about outcome.

usually when a form is valid it will trigger the native form post or a ajax request, so it should not matter whether the field remains in error state, since it will no longer be visible to the end-user.

could you describe in more detail how the workflow looks in your scenario?

**Comment by danielocdh** [comment]
@staabm It is a js/ajax form that when sent shows an overlay on top of the form with CSS like this:

    background: rgba(255, 255, 255, 0.2) url('images/ajax_loader.gif') center center no-repeat;

Right now I'm just manually removing the error class on the submitHandler, so this is fixed for me.
I still believe the behaviour is inconsistent, but is rare so you can fix it or just close this issue, thank you.
