### ISSUE TITLE
Custom method not working with number input

### ISSUE THREAD

**Issue by thdoan** [jzaefferer/jquery-validation#1656]
I noticed that a custom method using `addMethod()` will not work properly when validating numeric inputs (`type=number`). Steps to reproduce:

1. Go to my test case: http://codepen.io/thdoan/pen/zvVaed
2. Enter "902101110" into the text input and click outside to trigger the validation. The value should validate and change to "90210-1110".
3. Enter "902101110" into the number input and click outside to trigger the validation. ISSUE: The value disappears.

Here's an interesting observation: if you enter "90210-" into the number input, the `validateZip()` method is not even triggered (open the console to monitor).

**Comment by dkrahn** [comment]
Hi @thdoan 

From what I could see, the problem is the fact that a field of type number can have only digits. So when you add the '-' in your code, it clears the value since it is not valid. For the same reason when you type the '-' in to the field, the actual value stored is cleared. So it is empty and no validation is called.

You can see this when you type an invalid 3 digit value, focus out(will become invalid), type a valid 5 digit, focus out(will become valid) and now type a the '-', will become invalid. But if you read the message, it says it is a required field, meaning the value stored is empty.

From what I understand this is a native behavior. The '-' sign will only be usable at the start of a number for negative values.

Hope my explanation helps you.

**Comment by thdoan** [comment]
Hi @dkrahn, type="number" input fields accept numbers, dashes, and plus signs.

**Comment by dkrahn** [comment]
Hi @thdoan,
It does accept it at the right place.
See this fiddle I made with simple and pure JS: http://jsfiddle.net/dkrahn/cztnewvo/
When you type -123, meaning it's a negative number it stores the value. But when you type 123- the value is not stored, since it is not a number. The input allows you to type any character that can become a number, but only stores it when it becomes valid.

**Comment by thdoan** [comment]
Thanks for the fiddle. Were you able to figure out how to set the value to a number with a plus sign? I think if we are able to enter something manually, then we should be able to set set the field to that value using JS, but that doesn't seem to be the case.

**Comment by dkrahn** [comment]
Try this value: 2e+9
The limitation specified is due to the specification: http://www.w3.org/TR/html5/forms.html#number-state-(type=number)
As you can see the value cannot be set to an invalid number, but the input must allow some invalid input for the cases where the user is still typing the number like 2e+9 which only becomes valid after the last input.

**Comment by thdoan** [comment]
@dkrahn Thank you for the explanation -- the behavior makes sense now :+1:
