### ISSUE TITLE
Add 'dist' folder in repo

### ISSUE THREAD

**Issue by goffyara** [jzaefferer/jquery-validation#1786]
Please add actual 'dist' folder in the repository as here
https://github.com/twbs/bootstrap

It is not very convenient to use Composer and Bower.

**Comment by staabm** [comment]
please describe a bit more of your use-case. why do you need the dist folder?

As is I am not willing to introduce changes, without knowing the exact background.

will close for now, feel free to add further information. will re-open.

**Comment by denisz1** [comment]
+1 It was a breaking change to remove the `dist` folder, so existing systems cannot be updated/restored because.

Users expecting this feature for years, so need to stay, please.

[See also](https://github.com/jzaefferer/jquery-validation/issues/1877).
[Ans see also](https://github.com/jzaefferer/jquery-validation/issues/1420).
