### ISSUE TITLE
RequireJS dependency for additional-methods includes path

### ISSUE THREAD

**Issue by TrueWill** [jzaefferer/jquery-validation#1789]
### Subject of the issue
The RequireJS dependency for additional-methods includes a path.

`define( ["jquery", "./jquery.validate"], factory );`

This would be much easier to deal with if the line were

`define( ["jquery", "jquery.validate"], factory );`

### Your environment
jQuery Validation Plugin v1.15.0
Current Chrome

### Steps to reproduce
Attempt to include additional-methods via RequireJS (particularly when everything isn't in one folder and you have paths configs).

### Expected behaviour
It should load.

### Actual behaviour
404.

**Comment by staabm** [comment]
I have no experience with UMD/AMD. @Arkni any insights on this one?

**Comment by Arkni** [comment]
I have little experience with `RequireJS`, but AFAIK:

1. `define( ["jquery", "./jquery.validate"], factory );` means that the file `jquery.validate.js` should be in the same folder as `additional-methods.js` which is not always true (the additional-methods file can be put in other location).

2. `define( ["jquery", "jquery.validate"], factory );` means that the user need/have to define the path `jquery.validate` as follow:
```js
require.config({
    paths: {
        jquery: "path/to/jquery.js",
        "jquery.validate": "path/to/jquery.validate.js",

        // this is optional if we require the file directly
        "additional-methods": "path/to/additional-methods.js"
    }
});

// and then require them:

require(["jquery", "jquery.validate", "additional-methods"], function($) {

    $.validator.setDefaults({
        submitHandler: function() { alert("submitted!"); }
    });

    // validate the form when it is submitted
    $("#myForm").validate();
});
```

So yes, it should be easy if we use the second option. But, if we are going to do that change, we have to mention it in README and update the `RequireJS` demo to reflect that change.

One thing to mention is doing so will break things for people relying on the old behavior. What I mean is something like this will not work anymore:
```js
require.config({
    paths: {
        jquery: "path/to/jquery.js"
    }
});

// ....

// Note that jquery.validate.js and additional-methods.js are in the same folder
require(["jquery", "path/to/jquery.validate[.js]", "path/to/additional-methods[.js]"], function($) {

    $.validator.setDefaults({
        submitHandler: function() { alert("submitted!"); }
    });

    // validate the form when it is submitted
    $("#myForm").validate();
});
```

@TrueWill Am I wrong?

**Comment by staabm** [comment]
@Arkni thx so far.

@kelunik do you have experience with AMD/UMD and if so, could you say something about the requested change?

**Comment by kelunik** [comment]
@staabm Not really, sorry. Just used browserify with `require` so far.

**Comment by TrueWill** [comment]
I am no expert at RequireJS. I've been unable to get additional-methods to load in production, although it works in a plunk: http://plnkr.co/edit/30oQ0RZIJUspHXbqcIPc?p=preview

The only difference I can see between it and other modules that work is the inclusion of a path in the definition.

**Comment by staabm** [comment]
@jrburke any insights you could give?

**Comment by jrburke** [comment]
It depends on if 'additional-methods' is considered as part of the 'jquery.validate' package. I would think so, and if the CommonJS/node pathway in the UMD block in 'additional-methods' did not rely on an implicit dependency but instead asked for jquery.validate, it would use the relative './jquery.validate' as the dependency ID. If using [packages config](http://requirejs.org/docs/api.html#packages) in requirejs it would also be important to keep the relative ID.

So to me, the relative ID looks correct, and if the jquery.validate and additional-methods module IDs do not map to sibling paths on disk, I would recommend setting up the config so that they resolve correctly with the relative module ID for jquery.validate in additional-methods.

If the ID changes to just 'jquery.validate', which would make it a module ID rooted at the base of the module ID space, that would break people that use package managers where the related code is in separate package directories.

For the plunk example, I would recommend setting baseUrl to be the thirdparty/ location, and then using paths/packages config for anything else. 

This is how I generally recommend projects to be laid out: [baseUrl pointing to the "lib" or third party code, with a sing paths entry for the app area](https://github.com/volojs/create-template/blob/master/www/app.js), then all the app-specific code using relative IDs to refer to other modules in the app/ area.

**Comment by TrueWill** [comment]
As @jrburke is **the** authority on this, let's close this issue.

**Comment by camilonova** [comment]
In case someone else needed this is the working configuration (I'm using Yarn):

```
require.config({
    baseUrl: 'static',
    paths: {
        'jquery': 'node_modules/jquery/dist/jquery.min',
        'validate': 'node_modules/jquery-validation/dist/additional-methods',
        'localization/validateMessages': 'node_modules/jquery-validation/dist/localization/messages_es'
    },
    packages: [
        'jquery.validate',
        {
            name: 'jquery.validate',
            main: 'jquery.validate',
            location: 'node_modules/jquery-validation/dist/'
        }
    ]
});
```
