### ISSUE TITLE
Does not work with Materialize Selects

### ISSUE THREAD

**Issue by strideynet** [jzaefferer/jquery-validation#1830]
It only works with the Materialize selects if we use the browser-default class. This removes the great look that is given to it by Materialize.

I have also posted an issue on Materialize.

To reproduce create a Materialize Select input and a form and attempt to validate it. It ignores the select fields.

**Comment by Arkni** [comment]
> ... It ignores the select fields.

Because the `select` element is hidden. What `Materialize` render is a `div`

> It only works with the Materialize selects if we use the browser-default class

Using the class `browser-default` means that `Materialize` will use the `select` element and style it instead of replacing it with a `div`.

---
FYI, by default, `jquery-validation` ignores hidden and disabled elements and inputs of type `submit` and `reset`.

If you want to make it possible for the plugin to validate your `select` element, you should set [`ignore`](https://jqueryvalidation.org/category/plugin/#ignore) option to `""` or to selectors of elements that you want to ignore:

```js
$("#formId").validate({
  ignore: "",
  // ...
});
```

**Comment by strideynet** [comment]
Thank you so much. Just spent an hour or two trying to resolve this one issue!

**Comment by staabm** [comment]
will close for now. feel free to ask further questions.
