### ISSUE TITLE
Validating HTML input type='range'

### ISSUE THREAD

**Issue by wjroes** [jzaefferer/jquery-validation#1839]
Somehow validating does not seem to work on input type="range" elements (sliders) in HTML5. Checked Chrome and FF.

For the input element to work properly you need to add min, max and step attributes. However if these are used the validation always returns true. If I leave these out and add a rule in JS that adds a range it works as expected.

I have searched through the issue list but I haven't found any clear suggestions on why this should (not) work or how to get around it.

I am using version 1.15.0

Fiddle here https://jsfiddle.net/dr98hqL5/12/ showing both an input element that works and one that doesn't.

TIA
Willem

**Comment by YodaDaCoda** [comment]
I've checked your fiddle and found the following:

The first slider doesn't have rules attached to it, so it won't be validated.
The second slider doesn't have min and max values, so its value is always 0, which is outside the min/max rule set for it, so it's always invalid.

If you add the same validation rule to the first slider, it'll always be valid because the slider is limited to values of 3<=x<=10 by the browser. I.e. when the slider is right at the left, that represents a value of 3, not 0.

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
