### ISSUE TITLE
Validate Elements Based on ID Instead of Name

### ISSUE THREAD

**Issue by Jonnycake** [jzaefferer/jquery-validation#1851]
### Checklist for this issue
  * There should be a way to set which property the developer wishes to validate based on (ID/name)

### Subject of the issue
The library is currently selecting the element based on its name property which becomes a problem when multiple fields with the same name are on a page.

### Your environment
* 1.11.1
* FireFox, but any browser (as this is an unimplemented feature)

### Steps to reproduce
Attempt to set a rule on a field named the same as another field and observe that it isn't validated correctly (and assuming error placement is set up, the error gets placed in the wrong place).

### Expected behaviour
You should be able to decide if you want to look at the name or id property on the element that you're assigning rules to.

### Actual behaviour
It validates based on the name only.

**Comment by staabm** [comment]
so your form contains fields with the same name but different functionality ?

a more concrete example, e.g. a jsfiddle would help to clarify your use case.

**Comment by motou** [comment]
when inputs with the type of radio exist, then they could have all the same name property.
e.g.

<input type="radio" name="newsletter" value="YES">
<input type="radio" name="newsletter" value="NO">

Example:
https://api.jquery.com/attribute-equals-selector/

**Comment by staabm** [comment]
Radios and checkboxes with the same name are supported. Whats the issue you see?

**Comment by motou** [comment]
<input type="radio" name="terms" id="yes_button" value="YES">
<input type="radio" name="terms" id="no_button" value="NO">

The ids are used with styling/Dom-Manipulation etc., For example, if the validation is id-based, then I can say that I just want "no_button" checked.

**Comment by staabm** [comment]
I dont get your use case. The rules on radios apply for the whole group of radios. How should the lib decide whether a single element is valid (and against which rules)?

**Comment by motou** [comment]
if the element is picked up by name, I can only say the element "terms" is required, but what I need is actually a click of "yes" radio button. I cannot make the "Yes" button as required.

**Comment by motou** [comment]
In order to do that, I need to write a custom validation method to let the element group know, that only one option is allowed, but it's can be done easily if the elements are selected by id.

**Comment by staabm** [comment]
I still dont get what you are trying to achieve. It doesnt make sense to mark 1 radio of a radio-group required... if you need such strange rules a custom validator seems to be the way to go.

**Comment by strika** [comment]
Here's our use case (different, but related to the problem) - we have 2 forms on a page and both have a field with the `name` attribute value "email". And validation just doesn't work.

**Comment by staabm** [comment]
@strika which version of jq-validate do you use?

I dont know a case where it is not allowed to have equal-named input fields across forms. did you make sure to initialize the validator on each of your forms? did you nest the forms?

**Comment by strika** [comment]
We were using 1.13.1. But I just updated to 1.15.1 and it works the same.

Forms are not nested. And we initialized the validator only on one form. The second one is not using validations.

I'll try to provide a fiddle later today. Thanks.

**Comment by cybersubtype** [comment]
Their is also issues with file inputs, but that is related to file inputs only validating on a blur focus. Which talked about at #1869.

**Comment by strika** [comment]
@staabm I tried to recreate the problem in a fiddle, but couldn't. Then I went back to our code and found that the problem was that the field was missing the name attribute. So this was a false alarm. Sorry about that.

It's strange that we had one other field on the page where name attribute was missing, but validation worked correctly. We kept comparing these 2 fields to see what's different and couldn't find the problem. Only when we went back to check the documentation again, we tried to add the name attribute.

Again, sorry for the false alarm and thanks for your work!

**Comment by staabm** [comment]
Thx for coming back and providing the feedback.

**Comment by sanyamsingh** [comment]
One use case where Id is needed instead of name for defining rules. In rails name attributes are automatically created based on the name of the form object and fields. So if I want to make a generic rules file that works on all forms I need to have a way to refer to a generic name(id,class) so that anytime I want the rules to be applied to particular input I'll just give that input a generic name(id,class)
