### ISSUE TITLE
input-group and select2 css problem

### ISSUE THREAD

**Issue by mprandot** [jzaefferer/jquery-validation#1857]
Hello!

I have this structure :

```
<div class="form-group">
    <label> my label </label>
    <div class="input-group">
         <span>some span</span>
         <select class="select2"/>
    </div>
</div>
```

![captura de tela de 2016-09-08 11-37-29](https://cloud.githubusercontent.com/assets/14298396/18353817/dbfb285c-75b9-11e6-8345-1d68ce8d7bc8.png)

When the validator returns error the red border highlights only the span.
I'm searching for the error,but i can't find.

* version of `jquery-validate` : v1.14.0
* which browser and its version: Chrome, Firefox

**Comment by mprandot** [comment]
Update version to :  1.15.0, same problem.

**Comment by mprandot** [comment]
Someone can help?

**Comment by Arkni** [comment]
Can you create a [JSFiddle](https://jsfiddle.net/) to help identifying the issue ?

**Comment by mprandot** [comment]
@Arkni 

See : http://codepen.io/mprandot/pen/kkLAbO

**Comment by Arkni** [comment]
To make everything works as expected, you will need to use [`select2/select2-bootstrap-theme`](https://github.com/select2/select2-bootstrap-theme) in order to  make `Select2` fit in with Bootstrap 3.x, otherwise you'll have to hard code the CSS to style the select (see [this Stackoverflow question](http://stackoverflow.com/a/30785310/3904791)).

The following example is using the aforementioned theme: https://jsfiddle.net/Arkni/72185kg3/

**Comment by mprandot** [comment]
Thank's a lot!

Works like a charm! :smile:
