### ISSUE TITLE
MinLength accepts only white-space

### ISSUE THREAD

**Issue by kodecount** [jzaefferer/jquery-validation#1876]
## Subject of the issue
MinLength accepts white-space without any characters

### Your environment
* version of `jquery-validate`: 1.15.1
* which browser and its version: Chrome 53, Firefox 49, and IE 11

### Other discussions
https://github.com/wet-boew/wet-boew/issues/7557 

### Steps to reproduce
N/A

### Expected behaviour
MinLength should limit the minimum amount of characters.

### Actual behaviour
MinLength accepts all white-space without any characters.

### Possible fix
Change this line: https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L1374
To: `var length = $.isArray( value ) ? $.trim(value).length : this.getLength( value, element );`

Change this line: https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L1031
To: `return  $.trim(value).length;`

**Comment by kodecount** [comment]
This issue also applies to `required` method I believe at [Line 1324-1329](https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L1324) adding a `$.trim` well fix this. @Arkni @staabm @AbdullahObaid @jzaefferer

**Comment by Arkni** [comment]
@kodecount 

Trimming white spaces was dropped from core in 2ad0ca82daf091fc692018b38e01e896fd304015 as part of a fix for issue #1498, also see this comment https://github.com/jzaefferer/jquery-validation/issues/1354#issuecomment-67168988.

As a solution, we introduced a normalization layer in #1609 ([docs](https://jqueryvalidation.org/normalizer/)) that can be used to transform the value of an element before validation. This feature was available since `1.15.0`. In other words, you can do something like this:
```js
$("#myForm").validate({
  rules: {
    username: {
    required: true,
    // Using the normalizer to trim the value of the element
    // before validating it.
    normalizer: function(value) {
      // Trim the value of the input
      return $.trim(value);
    }
  }
});
```

**Comment by kodecount** [comment]
@Arkni Thanks a bunch for the information.

**Comment by JamoCA** [comment]
While Normalization is nice for client-side validation, when submitted it may not pass server-side validation.  I'm currently using this solution to auto-trim input fields:
https://github.com/jzaefferer/jquery-validation/issues/1354#issuecomment-257599334

NOTE: I added a ":input[data-rule-minlength]" to the selector because that's how we define the minimum character rule. Inputs with the class "noTrim" are ignored.

**Comment by Arkni** [comment]
@JamoCA 
For the record, the value of `this` inside the `normalizer` is the corresponding DOMElement. In my example above, `this` should reference the `username` element.

In other words, using `normalization` layer, you can trim and set the value of the element to the trimmed value:
```js
$("#myForm").validate({
  rules: {
    username: {
      required: true,
      // Using the normalizer to trim the value of the element
      // before validating it.
      normalizer: function(value) {
        // Trim the value of the input
        let trimmedValue = $.trim(value);

        // Set it as the new value of the corresponding element
        $(this).val(trimmedValue);

        return trimmedValue;
      }
    }
  }
});
```
