### ISSUE TITLE
presence of submitHandler causes custom handler to be run for cancel button

### ISSUE THREAD

**Issue by CapnSpellcheck** [jzaefferer/jquery-validation#22]
If I have a button with class cancel,the submitHandler I provided to validate gets called when it is clicked. I find it very puzzling - since it is not suposed to be doing validation, it should not call my handler but just return true:

if ( validator.cancelSubmit ) {
					validator.cancelSubmit = false;
					return handle();
				}

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
