### ISSUE TITLE
"error" class is not removed for disabled fields on validator.form()

### ISSUE THREAD

**Issue by aliquid** [jzaefferer/jquery-validation#224]
Successfully revalidating a form using validator.form() does not clear the "error" class from a field that is disabled (only the error message is removed).

Workaround:
  $("input.error").removeClass("error"); // watch out for the error message labels or they won't go away
  $("#myform").validate().form(),

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
