### ISSUE TITLE
Feature request: aria-required="true" when a field is required

### ISSUE THREAD

**Issue by Oire** [jzaefferer/jquery-validation#230]
Hi Jörn,
Thanks for your work and for this great plugin!
What I'd like to suggest is the following: if a field is required, it would be nice if the aria-required attribute would be automatically appended and set to true. That will improve accessibility of the forms.
Thanks!

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
