### ISSUE TITLE
.form() and .valid() on jQuery Validation 1.9 with jQuery 1.7

### ISSUE THREAD

**Issue by jimmyheaddon** [jzaefferer/jquery-validation#255]
I have several forms setup on jQuery tabs, each of which needs to be validated on an input change event seperate to one another (the idea being that a user cannot progress to the next tab without completing the previous form, with several key buttons disabled until a form is valid).  I have added some custom validation rules on top of a handful of MVC3 data annotations that I use (which individually work excellently).

If on input change I run the following code I notice that the .form() method returns the correct result, but the .valid() method and .errorList length are incorrect:

    var formValidator = $('#jQueryTabs #' + getSelectedjQueryTabName() + ' form').validate();
    if (formValidator.form()) {
        return true;
    }
    if (formValidator.valid() && formValidator.errorList.length == 0) {
        return true;
    }

However, I want to use the .valid() route as .form() causes all of my error messages and form input highlights to show every time I edit an input (even unrelated ones).  I think this is a bug?  I also want to be able to call .form() if the user attempts to click save at which point I will show all form errors, but not before.

A quick note that the above code is an example but is essentially what happens if I swap the .form() if statement out for a .valid() one.

Cheers

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
