### ISSUE TITLE
Highlight/unhighlight parent element of multiple fields

### ISSUE THREAD

**Issue by RichardLindsay** [jzaefferer/jquery-validation#268]
Hi,

I had an issue whereby I wanted to highlight the parent DIV of multiple elements if validation failed.

I achieved this easily with:

```javascript
highlight: function(element) {
$(element).closest("div").addClass("highlightError");
}
```

However, my issue arose when one of the fields in the DIV was correct. This meant that the highlight completely disappeared, even if other errors still remained.

To fix this I moved the unhighlight IF statement in the defaultShowErrors() function above the highlight FOR loop in the defaultShowErrors() function.

Now the highlighting remains until all fields in the parent element are correct.

I'm not sure if anyone is interested in this, I just thought i'd share it.

Cheers

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
