### ISSUE TITLE
Success callback failing.

### ISSUE THREAD

**Issue by morrisonlevi** [jzaefferer/jquery-validation#288]
With jQuery 1.7.1 and validate 1.9.0, the success callback is called every time the field is acted on, instead of only on success.  I observed this on several other versions of jQuery and validate as well.  Completely broken.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
