### ISSUE TITLE
showErrors gets called many times?

### ISSUE THREAD

**Issue by martijnthe** [jzaefferer/jquery-validation#320]
I noticed that showErrors gets called a lot of times. I haven't been able to pin down when exactly, but I've seen it happen once personally, but see it also in my analytics (I've a GA tracker that gets called inside the showErrors function).

Have you seen this happen before? Or should I be looking elsewhere for the problem...

Some background info:
* I've a `<img class="submit" type="img" ... />` as submit button of a form.
* The showErrors function is basically a copy of the default one, plus the GA tracker call and an `alert()` (I added this because I first thought people were bashing the submit button many times with an incomplete form).
* The one time that I saw this bug in person, was when I was filling one field and then backspacing until there was no text inside the input field any more.
* I am also using `Modernizr.input.placeholder` on the fields of the form.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by tueena-lib** [comment]
https://github.com/jquery-validation/jquery-validation/issues/2006
