### ISSUE TITLE
HTML5 Range input

### ISSUE THREAD

**Issue by Jontyy** [jzaefferer/jquery-validation#325]
I'm not 100% sure that this is an issue but after googling around it looks like the new input types are supported.

The plugin does not seem to like this:

```html
<input type="range" min="0" max="150" value="15"/>   
```

Very simple example on [jsbin](http://jsbin.com/utanar/edit#javascript,html,live)

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
