### ISSUE TITLE
Document remote dataFilter behavior

### ISSUE THREAD

**Issue by mlynch** [jzaefferer/jquery-validation#351]
There have been numerous requests for a more robust way to process the response from a remote validation call. Unfortunately, proposed solutions have not been adequate.

We've decided the best way to handle the response from your web service is to use the existing `dataFilter` option available on jQuery's `$.ajax` call. 

We need to provide documentation for how to take advantage of this. Here is an example that demonstrates how a user can process their server's response and return a form that validate can understand:

```javascript
form.validate({
	rules: {
		username: {
			required: true,
			remote: {
				url: "users2.json.php",
				dataFilter: function(data) {
					var json = JSON.parse(data);
					if(json.status === "success") {
						return '"true"';
					}
					return "\"" + json.error + "\"";
				}
			}
		}
	}
});
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by arsalannxb** [comment]
Thank you so much. i spent few hours for this.
