### ISSUE TITLE
Unable to overwrite old validator

### ISSUE THREAD

**Issue by kaluzar** [jzaefferer/jquery-validation#354]
Once you create a validator on a form you are unable to create a new one on it. The old one is always reused regardles of the options passed into the validate method. 

Example:
```html
<html>
  <body>
    <form id="myform">
      <input name="email" type="text"/>
      <input name="lastname" type="text"/>
      <button name="checkemail" type="button" onclick="checkemail()" >check email</button>
      <button name="checkall" type="button" onclick="checkAll()" >chek all</button>    
    </form>
  </body>
</html>
```

```javascript
function checkemail(){
        var validator = $('#myform').validate
		({rules: 
			{
				email: {required: true, email: true}
			}
		});
     var result = validator.form();
     alert(result);
}
function checkall(){
        var validator = $('#myform').validate
		({rules: 
			{
				email: {required: true, email: true},
				lastname: {required: true}
			}
		});
     var result = validator.form();
     alert(result);
}
```

In this scenario if you press check email button first and then check all button the validate method will return the old validator which validates the email only. Instead it should either create a new validator (since the options have changed) or the library should introduce a new method that would remove the old validator. The workaround for this is to run _$.data($('#myform')[0], 'validator', null);_ before invoking _$('#myform').validate_.

Since there is a workaround for this scenario I would say that this issue is rather low priority but it would be good to introduce a solution for it to make the the library more consistent.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
