### ISSUE TITLE
Grouped inputs aren't validated on any event other than submit

### ISSUE THREAD

**Issue by richardscarrott** [jzaefferer/jquery-validation#364]
Given this form:

    <form method="post" action="/wherever">
        <div class="-field field-expirationMonth">
            <select name="card_expirationMonth" id="card_expirationMonth">
                <option value="">MM</option>
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="etc">Etc</option>
            </select>
        </div>
        <div class="-field field-expirationYear">
            <select name="card_expirationYear" id="card_expirationYear">
                <option value="">YY</option>
                <option value="2012">12</option>
                <option value="2013">13</option>
                <option value="2014">14</option>
                <option value="2015">15</option>
                <option value="etc">Etc</option>
            </select>
        </div>
    </form>

And the following validation:

    $('form').validate({
        rules: {
            card_expirationMonth: 'required',
            card_expirationYear: 'required'
        },    
        groups: {
            cardExpiration: 'card_expirationMonth card_expirationYear'
        },
        errorPlacement: function (error, element) {
            if (element[0].name === 'card_expirationMonth' || element[0].name === 'card_expirationYear') {
                 error.prependTo('form');
            }
        }
    });

It can be seen, on focusout, that the error message will be removed even though one of the two inputs isn't valid.

Interestingly enough the groups demo: http://docs.jquery.com/Plugins/Validation/validate appears to disable onkeyup, onfocusout, onfocusin which means the issues isn't noticed.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
