### ISSUE TITLE
jquery mobile ui - conflicts

### ISSUE THREAD

**Issue by programmermattsrum** [jzaefferer/jquery-validation#416]
I am trying to use jquery validation on the mobile platform.  It is working fine on the desktop version, but it seems to have an issue with the controls for jquery mobile like the checkbox.  I don't think it has an issue with the dropdown control, but it is having issues with the checkbox for sure.  I try to remove the rules from the page so it doesn't validate it, but it always gets stuck prior to the checkbox control.   I am thinking though it has something to do with the jquery mobile ui that is wrapped around it.   If there is anyway you can help let me know.

Search for "This field is required."

Error on page - "Uncaught TypeError: Cannot read property 'form' of undefined" 

Thanks,

Matt

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
