### ISSUE TITLE
validate specific method on keypress (not all methods tied to field)

### ISSUE THREAD

**Issue by ghost** [jzaefferer/jquery-validation#417]
validating each field on blur:

//validate each element on blur
    $('input, select, radio, checkbox').blur(function(){
        $("#createAccount").validate().element(this);
    });

I added an additional method for passwords - alpha, numeric, no spaces/dashes:

//Additional validation methods:
jQuery.validator.addMethod("passwordCheck", function(value, element) {
    return this.optional(element) || /^[a-zA-Z0-9]+$/.test(value);
}, "Invalid characters");

A couple of issues:

I would like to validate the password field on blur for everything but the passwordCheck method. So other methods, such as required, should validate on blur - but if an invalid character is entered, then I want the validator to trigger that method on keypress.

Additionally, when adding methods, is there a way to get the error message into the messages portion of the validation call (just to keep them all in one place)?

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
