### ISSUE TITLE
numberOfInvalids() doesnt account for groups

### ISSUE THREAD

**Issue by simshaun** [jzaefferer/jquery-validation#42]
For example:

1. There are 3 required fields on a form.
2. 2 of them are grouped using the groups option
  *This causes 2 errors to be displayed

Calling numberOfInvalids() in invalidHandler returns 3 (there were indeed 3 total errors), but only 2 errors are displayed.

I think there needs to be a way to get the number of errors that are displayed to the user.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
