### ISSUE TITLE
element method throws an error with 'checkable' inputs if they are not currently displayed

### ISSUE THREAD

**Issue by cranberrynut** [jzaefferer/jquery-validation#422]
If you have a checkbox which is currently not being shown - e.g., if it is in a form where 'display: none' is set on the parent element - and call the element() method on it, the plugin throws an error.  The reason I've found is this:

element() calls validationTargetFor(element), which is defined as:
```js
		validationTargetFor: function(element) {
			// if radio/checkbox, validate first element in group instead
			if (this.checkable(element)) {
				element = this.findByName( element.name ).not(this.settings.ignore)[0];
			}
			return element;
		}
```
Because the default 'ignore' setting is now ':hidden' in 1.9, this means elements whose parents have been set to display:none are ignored and the element returned from this method is undefined.  Then when returned to the element() method, it blows up upon trying to get a reference to undefined.

I understand that you can easily avoid this problem by emptying settings.ignore prior to calling element(), but I think the plugin should not be blowing up with an error in this case.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by dnxit** [comment]
I faced that issue with checkboxes & hidden inputs on the form in MVC 5 Jquery 3.3.1, nothing worked so I had to disable the default validation and do some custom validation.

<button type="submit" id="btnSubmit" formnovalidate="formnovalidate" class="btn">Submit</button>
