### ISSUE TITLE
Supporting Fields With Same Name

### ISSUE THREAD

**Issue by benlilley** [jzaefferer/jquery-validation#423]
First thank you for all your work on this plugin, it has made my life easier on many occasions. The reason I'm submitting this issue is because today I ran into an issue where I needed to validated fields with the same name, something like: `<input type="text" name="foo[]" value="" />` - the problem is the plugin will only validate the first field with this name which I'm sure you know.

I spent a while looking for solutions but couldn't find any that worked correctly until I [stumbled on this](http://stackoverflow.com/a/4136430/432513). This works perfectly! The general idea that you update the checkForm function to this:

```
checkForm: function() {
			this.prepareForm();
			for ( var i = 0, elements = (this.currentElements = this.elements()); elements[i]; i++ ) {
				if (this.findByName( elements[i].name ).length != undefined && this.findByName( elements[i].name ).length > 1) {
					for (var cnt = 0; cnt < this.findByName( elements[i].name ).length; cnt++) {
						this.check( this.findByName( elements[i].name )[cnt] );
					}
				} else {
					this.check( elements[i] );
				}
			}
			return this.valid();
		},
```
Is this a viable solution? If so is it possible to get this implemented into the core to solve issues in the future?

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
