### ISSUE TITLE
remote validation data

### ISSUE THREAD

**Issue by ryleyb** [jzaefferer/jquery-validation#424]
I just read an interesting problem someone was having over at <a href="http://stackoverflow.com/q/10597286/312208">StackOverflow</a>.  You can see my answer there, but the summary is this:  remote validation takes all the parameters provided to the remote rule and extends an ajax request with them.  There's no way to pull in information about the element being validated (beyond the default of field name -> value) and send it across to the remote url, unless you know the name of the element being validated beforehand (which defeats the beauty of using addClassRule).  

I think the idea has a lot of potential, and if anyone has ideas for an elegant way to allow this, I'm quite willing to code it.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
