### ISSUE TITLE
Default Value with Remote do not validate

### ISSUE THREAD

**Issue by aslamdoctor** [jzaefferer/jquery-validation#433]
I am having just 3 fields in a form as contact_person, email and invitation_code
All are textboxes and all has validations as below Code.
But when I submit the Page, it do not validate or don't even show any error on console.

One thing is, I have set default value of the invitation_code textbox to 123456 so that some users can leave it as it is.
If I remove this default value from textbox then this validates properly.

Please advice.

```javascript
$(document).ready(function(){
			
			$("#frmAdd").validate({
				errorElement: "label",
				errorClass: "error-input",
				rules: {
					contact_person: {	required: true },
					email: {   required: true, email: true },
					invitation_code: { 
						required: true, 
						remote: {
							//check if invitation_code exists or not
							url: "check_exists.php",
							type: "post",
							data: {
								invitation_code: function() {
									return $("#invitation_code").val();
								}
							}
						}
					}
				},
				messages: {
					contact_person: {	required: "Please enter Contact Person" },
					email: {   required: "Please enter Email address", email: "Please enter valid Email address" },
					invitation_code: { required: "Please enter User Invitation Code", remote: "User with this Invitation Code already exists" }
				}
			});

		});
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
