### ISSUE TITLE
Inconsistent behaviour for immediate validation. 

### ISSUE THREAD

**Issue by JimBobSquarePants** [jzaefferer/jquery-validation#435]
When running the plugin with the settings:

    onkeyup: false,
    focusCleanup: false,
    focusInvalid: false,
    onfocusin: false,
    onfocusout: false,

All inputs other than selects, radiobuttons and checkboxes will not automatically validate but *will* validate on submit. This causes inconsistency in display behaviour. 

Disabling the behaviour using `onclick : false` prevents the immediate validation but also appears to disable all validation for the nodes despite the required method returning false for value length.

At present it appears impossible to provide a consistent user experience for forms utilizing a validation summary as the page will jump.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by JimBobSquarePants** [comment]
Crikey! This was a long time ago... I reckon it's probably long since been sorted simply through gradual updates. The internals have changed quite a lot over the years. I'll have a look when I get a mo though and run some tests.
