### ISSUE TITLE
rules('add', ...) affects other elements

### ISSUE THREAD

**Issue by fdevibe** [jzaefferer/jquery-validation#439]
With

&lt;form id="foo"&gt;
  first: &lt;input type="text" id="first"&gt;&lt;br&gt;
  second: &lt;input type="text" id="second"&gt;&lt;br&gt;
&lt;/form&gt;

and

$(document).ready(function() {
  $('#foo').validate();
  $('#first').rules('add', {min: 2});
  $('#second').rules('add', {min: 4});
});

both #first and #second end up with a min value of 4. If the js block is exchanged with

$(document).ready(function() {
  $('#foo').validate();
  $('#first').attr('min', 2);
  $('#second').attr('min', 4);
});

#first gets a min value of 2 and #second a min value of 4 (which is what I would expect).

This also seems to be the case for other rules.

Tested using FF 12 (Linux amd64), using validate 1.9 and both jquery 1.6.1 and 1.7.2.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
