### ISSUE TITLE
resetForm() not reseting numberOfInvalids() when switching between ignoring hidden and none hidden fields for validation

### ISSUE THREAD

**Issue by mouaxiong** [jzaefferer/jquery-validation#440]
I know that there was a fix which did fix an earlier issue with the resetForm() not working.  HOwever, after that it was still not resetting the numberOfInvalids() back to 0 and retaining the values if the default ignore was set to also validate hidden fields.

As a temporary fix around this, I had to add the line "this.invalid = {};" to line 410 in jquery.validate.js to correctly reset the value back to 0 when resetForm() is called.

Please let me know if there's a better solution to this.  Otherwise please test to confirm and let me know when this is fixed as I don't want to keep these custom fixes in jquery.validate.js.  Thanks for your help.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
