### ISSUE TITLE
range="13,23" doesn't work, nor does range="[13,23]" in markup

### ISSUE THREAD

**Issue by rikkipitt** [jzaefferer/jquery-validation#447]
Hi guys,

When using range="[13,23]" or range="13,23" - the validation fails unless the number inputted is 1 - 3.

I think the line below is the culprit (doesn't seem to listen to the array or series of numbers correctly):

```js
rules[this] = [Number(rules[this][0]), Number(rules[this][1])];
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
