### ISSUE TITLE
Custom context specific error messages for validation Methods

### ISSUE THREAD

**Issue by jvetyska** [jzaefferer/jquery-validation#449]
I cannot figure if there is a way for a validation method to return context specif error message. 
When adding a method, I can only specify a error message that can accept parameters from the rule params.

For remote validation, the result will be displayed as a error message. How can I do the same from within a validation method?
So for example I can return error message showing the user's input, such as: "asdf" is not a valid name.

**Comment by pljspahn** [comment]
Has there been any movement on this in the last two and a half years?

I am facing a similar situation. I have two select fields that allow a user to choose a size dimension in inches, one select for whole inches, one select for fractional inches. This structure repeats in other areas of the form, ie I have two select inputs for width, two for height, two for inner width, two for inner height, two for top border width, two for top border height ... etc etc.

Some of these inputs need to check the values of other inputs to determine validity. For example, the inner width should always be less than the outer width. Since those values can vary, I would like to supply the user with an error message that is useful. Consider the following method I have added:

	jQuery.validator.addMethod('lessthancombo', function(v, e, p){
		var isValid = false;
		var params = p.split(',');
		if (parseFloat(jQuery(params[1]).val()) < parseFloat(jQuery(params[0]).val())) {
			isValid = true;
		};
		return isValid;
	}, '{0} is invalid');

I would like the message to be more along the lines of "Inner Width must be less than Outer Width of 30" - I can't see how this can be done without adding a ton of bloat to the markup.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by pljspahn** [comment]
Personally, I ultimately switched my application to Angular as jQuery was simply proving too problematic to work with. What an eye opener. I hope to never have to rely on jQuery again.

**Comment by thicongtu2** [comment]
you can re-define message error and pass param to it like:
$.extend($.validator.messages, {
        required: "{1} is not empty!";
    });
and in rules:
rules: {
            name: {
                required: [true, "Name"]
            }
}
