### ISSUE TITLE
Check file size for upload in supported browsers using HTML5 File API

### ISSUE THREAD

**Issue by niftylettuce** [jzaefferer/jquery-validation#450]
This is a mix between jquery-validation and Modernizr, although we can port the Modernizr part out so Modernizr is not a dependency.

I'm wondering if you are open to having me add it to additional-plugins?  It is a great feature :)

```js
  // Validate file input on change
  jQuery.validator.addMethod("filesize", function(value, element, param) {
    // This requires Modernizr filereader community add-on:
    // <https://github.com/Modernizr/Modernizr/blob/master/feature-detects/file-api.js>
    var valid = true;
    if (Modernizr.filereader) {
      // Check if file size is valid
      // (e.g. value = "10485760" = 10mb)
      for(var i=0;i<element.files.length;i+=1) {
        if (element.files[i].size > param) valid = false;
      }
    }
    return this.optional(element) || valid;
  }, "File exceeds maximum upload size.");
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by twolfson** [comment]
If anyone is still interested, I have created #1512 in order to create a maximum file size plugin
