### ISSUE TITLE
datejs alternative

### ISSUE THREAD

**Issue by lb1a** [jzaefferer/jquery-validation#453]
I read your todo file and stumbled upon the notice of checking out "datejs.com" for a date implementation. i used that too and had many little issues and as you already said: it's way to oversized.
I'm using moment.js at the moment as an lighweight alternative. maybe checkout this js lib ?

http://momentjs.com/
https://github.com/timrwood/moment

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
