### ISSUE TITLE
Include selector

### ISSUE THREAD

**Issue by penhorwood** [jzaefferer/jquery-validation#454]
Currently you have the ignore setting that is used on line 461 .not( this.settings.ignore ).  I am suggesting you add settings.include value.  It would look like this in the code.

.not( this.settings.ignore )
.add( this.settings.include )

The purpose is to add back fields that need special handling.  I have a situation where I have <input type="hidden"...> that I want ignored all except one that is firing a custom validation method.  By adding this one line of code and a setting I am able to add my field back to the mix.

Andrew Penhorwood

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
