### ISSUE TITLE
Incorrect API instructions causes error in events

### ISSUE THREAD

**Issue by allpro** [jzaefferer/jquery-validation#456]
This is not a code bug per se - it is really a documentation error, but one that results in broken code.
All of the event options (keyup, focusout, etc) say that the value is a "boolean". This is incorrect. The value is actually a callback method. If you set this to "false", it effectively 'disables' that event, BUT if you set the option to "true", it generates errors because the delegateValidation method tries to do this: true.call(...).

I can see where it may be useful to create custom callbacks - assuming they will work? But the documentation should clearly specify that this is what they are. I just wasted an hour trying to figure out why I was getting errors. I finally realized it is because I has set some events to "true" in my options. I was testing various things so it seemed more logical to toggle the options true/false, since the docs said these options were simple boolean values.

As I said, this does not require code changes, though it would be a good idea to add a check to ensure these options are actually functions before trying to call() them. Still need to update the API doc though.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
