### ISSUE TITLE
Add validHandler support

### ISSUE THREAD

**Issue by ericjohannsen** [jzaefferer/jquery-validation#459]
The jQuery validate plugin has an invalidHandler init function which gets triggered if something is invalid.  However it does not have anything for validHandler where you you want trigger something immediately if validation succeeds (i.e like hide something).

There is a suggested code change here to resolve this issue:

http://forum.jquery.com/topic/suggestion-for-validate-plugin

The issue is also discussed here:

http://stackoverflow.com/questions/11334365/jquery-event-when-validation-errors-corrected

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by IsQiao** [comment]
you can implement similar thins like this:
```javascript
var validator = $("#signin_form").validate({
        rules: {
            Phone: {
                required: true,
                phone: true
            },
            VerifyCode: {
                required: true,
                verifyCode: true
            }
        },
        messages: {},
        success: function (label, element) {
            if (validator.numberOfInvalids() == 0) {
                console.log(true);
            }
        }
    })
```
