### ISSUE TITLE
Bug with field group error label on validation

### ISSUE THREAD

**Issue by CodeTheInternet** [jzaefferer/jquery-validation#462]
When coding a form that has a group of fields together (such as for a phone number, credit card number or SSN), there is an issue with the error label message display.

One can have an error state on the first few fields of the group, but if the most recent field edited/validated is valid, the error label is display:none

EXAMPLE:
Validate a US phone number. All fields required, digits only, maxlength 3,3,4 respectively. 
If the first field has 'A' (invalid), second is not filled in (invalid), third has '1234' (valid), the group error label is not shown. The individual input fields still have 'error' class on them, as expected.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
