### ISSUE TITLE
Syntax for using equalTo in class/data attribute

### ISSUE THREAD

**Issue by carlospictor** [jzaefferer/jquery-validation#465]
Hi,

Is there a way to use equalTo within the class of an element, similar to:

class="{required:true, rules:{equalTo: '#password'}}"

I've tried a few permutations that don't seem to work, and wonder if I'm missing something?

**Comment by tilt-me** [comment]
Hi Carlos,
you can use the equalTo attribute in an input element, this way:
<input id="confirm_password" name="password" equalTo="#password" />
Source: https://forum.jquery.com/topic/validate-apply-equalto-rule-inline-to-input-class

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
