### ISSUE TITLE
Error class on radio buttons

### ISSUE THREAD

**Issue by WebPhenom** [jzaefferer/jquery-validation#469]
After one uses the reset button to reset a form and clear all the errors using:

// resets form and errors via the reset button
    $("#reset").click(function () {
        validator.resetForm();
    });

All the errors do get cleared but there is a problem with Radio Buttons. Radio buttons have the same name and if you have a YES  |  NO radio buttons, the rest takes off the error class only on the first instance of the radio button names, so the YES button is OK. The NO button still has the error class on it if you check in Firebug. This is problematic if you style the error input fields.

How does one clear the 2nd radio button as it has the same name and should be cleared, no?

Thanks.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
