### ISSUE TITLE
Select box with focusCleanup doesn't hide error

### ISSUE THREAD

**Issue by itsnydell** [jzaefferer/jquery-validation#472]
I am using the latest jquery & jquery.validation plugin. 

My Javascript code looks like this
```javascript
$(function() {
	$("#signup").validate({
		onkeyup: false,
		errorElement: "span",
		errorPlacement: function(error, element) {
			error.insertAfter(element);
		},
		rules: {
			// ... 
			card_exp_year: {
				required: true,
				hasselected: true
			}
			// ... 
		},
		submitHandler: function(form) {
			form.submit();
		}
		debug: true,
		ignore: "",
		focusCleanup: true
	});
});

jQuery.validator.addMethod("hasselected", function(value, element) { 
  return this.optional(element) || value != "0"; 
}, "Please select an item.");
```

My html code looks like this
```html
<form id="signup" action="next_page.html" method="post">
	<select name="card_exp_year" class="full" title="Please select an experation year.">
		<option value="0">YYYY</option>
		<option value="2012">2012</option>
		<option value="2013">2013</option>
		<option value="2014">2014</option>
		<!-- ... -->
	</select>
	<input type="submit" class="button blue" value="Next">
</form>
```

**My problem** is that when selecting an option that is to throw an error, when I go to click on the select box again, the error is supposed to hide like all other form elements. I have "focusCleanup: true" set. 

**Steps to take to replicate my problem**:
Click Select box
Select 2012
Click outside box
Click select box
Select YYYY
Click outside box
*Error message shows*
Click select box
*Error message disappears and then reappears right away.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
