### ISSUE TITLE
Make cancel buttons a setting

### ISSUE THREAD

**Issue by Jelle-S** [jzaefferer/jquery-validation#473]
At the moment, buttons with the 'cancel' class don't trigger validation. It would be nice if this was a setting we could pass through. We especially need this at our Drupal module [Clientside Validation](http://drupal.org/project/clientside_validation) where we do not control the classes buttons may or may not have. See related [issue](http://drupal.org/node/1707032) in our issue queue.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
