### ISSUE TITLE
Buggy regexp in the additional method jQuery.validator.minWords()

### ISSUE THREAD

**Issue by Proteo** [jzaefferer/jquery-validation#477]
The regexp used in the minWords() method generates the following error: 

__TypeError: value.match(/\b\w+\b/g) is null__

When you enter only commas in the validating field, for example the string ",,,,,,,"

That actually makes the script crash which results in the form not being validated at all. Tested in Mac OS X Lion, Firefox 14.0.1 with Firebug 1.10.2, jQuery Validation v.1.9.0.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
