### ISSUE TITLE
When left blank, optional elements are silently counted as invalid

### ISSUE THREAD

**Issue by sbandyopadhyay** [jzaefferer/jquery-validation#481]
**The short version.**
See the error for yourself: http://jsfiddle.net/r4F4L/

As noted in the [documentation](http://docs.jquery.com/Plugins/Validation/Validator/numberOfInvalids) for `numberOfInvalids()`, one can provide callbacks for `invalidHandler` (or `showErrors`, etc.) that use `numberOfInvalids()` to summarize the total number of errors.

When an optional field (that is, any field using a validation method that calls `this.optional(element)`) is left blank, that field is counted as invalid, and `numberOfInvalids()` returns 1 greater than it would otherwise.

There is no error message displayed -- which is the desired functionality! -- but that means that this field is essentially counted as invalid silently.

**How to replicate this error.**
See it here live: http://jsfiddle.net/r4F4L/

Set up a form with a field that has just one rule: 'number'. (Note that this field is not required.)

Specify the `showErrors` parameter when setting up the validation, like so:
```javascript
$('#myForm').validate({
  rules: {
    myField: 'number'
  },
  showErrors: function(errorMap, errorList) {
    console.debug('Number of errors: '+ this.numberOfInvalids());
    this.defaultShowErrors();
  }
});
```

Now enter a number for the field, so that it validates correctly. So far, so good.

Now delete the number out of the field. The console.debug() will print out the number 1, even though there is no error!!

**Why this may be happening**
`this.optional(element)` returns "dependency-mismatch" when the optional field is left blank.

`number()` [returns "dependency-mismatch"](https://github.com/jzaefferer/jquery-validation/blob/1.9.0/jquery.validate.js#L1050-1052), because it got that from `this.optional(element)`.

`check()` [receives "dependency-mismatch"](https://github.com/jzaefferer/jquery-validation/blob/1.9.0/jquery.validate.js#L507-510) and then [returns undefined](https://github.com/jzaefferer/jquery-validation/blob/1.9.0/jquery.validate.js#L528-529) as a result.

`element()` receives back `undefined`, and as a result [marks this element as invalid](https://github.com/jzaefferer/jquery-validation/blob/1.9.0/jquery.validate.js#L356-361).

**Issues this may be related to?**
#37: depency-mismatch

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
