### ISSUE TITLE
Remote w/ ASP.NET (IIS) should check for .d

### ISSUE THREAD

**Issue by DR9885** [jzaefferer/jquery-validation#483]
Currently I have a ASP.NET 4.0 WebForms application. It has an ASMX WebService called CheckPassword. When I try to return an Error string, asp.net wraps the object with a variable called "d". I have a reference explaining more about how to resolve this issue...

Reference: http://encosia.com/never-worry-about-asp-net-ajaxs-d-again/

For now my solution is to have a dataFilter used as follows...

if (response.d != undefined) { response= response.d; }

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
