### ISSUE TITLE
Remote Caches Value Returned from fucntion

### ISSUE THREAD

**Issue by DR9885** [jzaefferer/jquery-validation#485]
Remote functionality isn't working as documented, it seems to be caching the data at load, the temporary fix I found was to wrap the remote data into a function... Not sure if the documentation should change, or this bug should be fixed.

Fix Listed Here:
============
http://stackoverflow.com/questions/3170778/jquery-validation-plugin-remote-method-data-issue

Documentation Example: http://docs.jquery.com/Plugins/Validation/Methods/remote
=================
     remote: {
        url: "check-email.php",
        type: "post",
        data: {
          username: function() {
            return $("#username").val();
          }
        }
      }

My Current Implementation:
=========================
                          remote: function () {
                                return {
                                    url: "Services/User.asmx/PasswordCheck",
                                    contentType: "application/json; charset=utf-8",
                                    dataType: 'json',
                                    type: "post",
                                    // Filter out MSft Wrapper
                                    dataFilter: function (data) {
                                        data = JSON.parse(data);
                                        if (data.d != undefined) { data = data.d; }
                                        if (data == "true") { data = true; }
                                        return JSON.stringify(data);
                                    },
                                    data: JSON.stringify({ password: $('#<%= txtNewPassword.ClientID %>').val() })
                                };
                            }

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
