### ISSUE TITLE
validation error container display when it shouldnt

### ISSUE THREAD

**Issue by designingit** [jzaefferer/jquery-validation#489]
Hello,

I downloaded newest code today but I am having problems with my validation. I am using the errorcontainer-demo.html as my example. this is what my form looks like http://cl.ly/image/0q0I3C45311s
when I start typing in the email field, after about the 3 character, the error container fades in, and shows ALL the fields. however, i havent even typed in the rest of the fields yet, nor have i completed the email field. 

any thoughts??

code:

<script type="text/javascript">
$().ready(function() {
	
	var container = $('div.error-container');
	// validate the form when it is submitted
 var validator = $("#regForm").validate({
        errorContainer: container,
        errorLabelContainer: $("ol", container),
        wrapper: 'li'
        ,debug: true
        ,meta: "validate"
    });
	
});
</script>

thanks
Florian

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
