### ISSUE TITLE
Browser's autofill triggers validation - is this preventable?

### ISSUE THREAD

**Issue by Einkoro** [jzaefferer/jquery-validation#495]
Normally when you type into the fields and tab to the next validation doesn't occur until clicking submit - if there is an error it will then validate onkeyup and onclick. However, if the browser autocompletes for you, it will immediately trigger validation. Is it possible to prevent validation when the browser autofills the fields?

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
