### ISSUE TITLE
How to submit form for each header section

### ISSUE THREAD

**Issue by nutlessNeo** [jzaefferer/jquery-validation#498]
I have an accordion with 4 headers/sections, each having a form inside it. I am needing to have each form be submitted to the server and a callback given, as well as the validation. I have the validation working - i guess - i just used the default settings. but how do I get a callback for each form being submitted? 

Thanks in advance..

p.s. if this has already been addressed - forgive me - but I couldn't find anything in the closed or open issues.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
