### ISSUE TITLE
Should fire custom events

### ISSUE THREAD

**Issue by jasonkarns** [jzaefferer/jquery-validation#504]
There are all sorts of events that we should be able to hook into to trigger additional behavior. How can it be that this plugin doesn't fire a single event that can be bound to?

The event I'm personally most interested in is afterFormValidate. However, there are a slew of other potential hooks that people need access to:

- beforeFormValidate
- beforeResultsShown
- beforeFieldValidate
- afterFieldValidate
- afterFormValidate
- etc.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
