### ISSUE TITLE
success function not picked up in global settings

### ISSUE THREAD

**Issue by steveworkman** [jzaefferer/jquery-validation#516]
n.b. I'm using .net MVC 4 with jQuery validate 1.10 and the unobtrusive addition

I'm trying to have a success function run to indicate that the form input is correct. I'm putting this in my global settings like this:

```
jQuery.validator.setDefaults({
    success: function (label) {
        console.log("Succeeding");
        $(label).text('OK!').addClass('valid');
        $(label).closest('.control-group').removeClass('error').addClass('success');
    },
    highlight: function (label) {
        $(label).closest('.control-group').removeClass('success').addClass('error');
    }

});
```
The highlight method is called, but the success method doesn't get called.

When I step through to the library - it gets to defaultShowErrors and when it tries to run this
```
if (this.settings.success) {
    for (i = 0; this.successList[i]; i++) {
           this.showLabel(this.successList[i]);
     }
 }
```
and I inspect this.settings.success, I get this:
```
function () {
			return fn.apply( context, args.concat( core_slice.call( arguments ) ) );
		}
```
Which isn't what I set.

Why is the code not being called? How should I be doing this?

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
