### ISSUE TITLE
Remote validation clears validationmessages of the fields above the field with remotecheck

### ISSUE THREAD

**Issue by 11mb** [jzaefferer/jquery-validation#517]
First I added a comment on this thread: https://github.com/jzaefferer/jquery-validation/issues/12
But my situation is slightly different.

When I have a form with remote-validation and using async=false all errormessages of the fields above (in html) won't be shown.

I provided some sample code:
http://stackoverflow.com/questions/12475350/jquery-validate-remote-bug

You'll see that validation works when the remote-validation-field is the first field in the form.. but when moved to the end, no error messages but the one from the remote-check will be shown.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
