### ISSUE TITLE
groups issue - errors go away even though there is still validation errors in the group.

### ISSUE THREAD

**Issue by programmermattsrum** [jzaefferer/jquery-validation#530]
Here is an example - http://jsfiddle.net/G4rNm/

Each row is a group in this example

<p style="color:red"><b>Step 1 :</b></p> 
     On Round 1 on the 2nd row enter 555 into C1 column.

<b>Expected output - </b>

 "Please enter a value less than or equal to 150."

<p style="color:red"><b>Step 2 :</b></p> 
     On Round 2 on the 2nd row enter -1 into C2 column.

<b>Actual output   - </b>

Please enter a value greater than or equal to 0.

<b>Expected output - </b>

"Please enter a value greater than or equal to 0.
Expected output - "Please enter a value less than or equal to 150."

<p style="color:red"><b>Step 3 :</b></p> 
     Now, remove -1 on 2nd row on C2 column

<b>Actual output - </b>

"" (Nothing)

<b>Expected output -</b>

"Please enter a value less than or equal to 150."

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
