### ISSUE TITLE
Form does not submits using AJAX in IE7 and IE8

### ISSUE THREAD

**Issue by nirajmchauhan** [jzaefferer/jquery-validation#531]
I am trying to submit a form through ajax using GET method. It works fine in FF, CHROME and other browsers except IE7 and IE8. I am using jQuery 1.6 and I am validating the form using jQuery Validation Plugin 1.10.0 (minified version)

Form is getting validated but when I try to submit it refreshes the page instead of AJAX. In console its not displaying any error. The problem is not of AJAX, if I remove the validation code then the form is getting submitted in IE7/8 using AJAX

Heres my JS Function

```
function formSubmit(formID, displayMssgID) {
    jQuery(function($) {
        var qstring = $('#' + formID).serialize();
        jQuery.validator.addMethod("notEqual", function(value, element, param) {
              return this.optional(element) || value != param;
            }, "Please enter your name.");
        var val = $('#' + formID).validate( {
            rules : {
                Mobile : {
                    number : true,
                    minlength : 8
                },
                Name: {
                    required: true,
                    notEqual: "Name"
                }
            }
        }).form();
        if (val) {
            $('.overlayss').fadeIn();
            $('#prospectLoading').fadeIn();
            $('#prospectLoading').append('<div class="process_img"> Registering your Request ...<br />Please Wait ...</div> ');
            $.ajax( {
                url : "index.php",
                data : qstring,
                cache:false,
                success : function(data) {

//                  resetFormFields(formID);
                    if(formID == 'siteVisit'){
                        $('#cart ul').html('');
                    }

                    //$('#' + displayMssgID).html('');
                    $('#prospectLoading').html('');
                    $('#prospectLoading').append(data);
                    //$('#' + displayMssgID).append(data);                  
                    window.setTimeout(function() {
                        $('#prospectLoading').html('');
                        $('.overlayss').fadeOut();
                        $('#prospectLoading').fadeOut();
                    }, 4000);                   
                }
            });
        }
    });
}
```

You can check the live example on this link http://www.silverline-group.com/projects/Bangalore-Properties.html

Fill up the form on the right sidebar in IE7 or IE8.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
