### ISSUE TITLE
Support for HTML5 form-associated elements

### ISSUE THREAD

**Issue by IwanVosloo** [jzaefferer/jquery-validation#534]
HTML5 allows one to have inputs that are not physically contained within a form, yet are still seen as part of that form ( see http://dev.w3.org/html5/spec/single-page.html#form-associated-element ).

This makes it possible to create a form which has children (in the DOM) that are inputs, but that are not logically part of the form that contains them.

In this scenario, jquery validate breaks, because it tries to validate all inputs that are contained in the form, not taking into account the form they actually belong to.

Similarly, jquery validate does not validate the inputs associated with a given form if they're not physically contained within the form they are associated with.

See an example of the first scenario at: http://jsfiddle.net/IwanVosloo/gUxaQ/

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
