### ISSUE TITLE
keyup validation triggering is inconsistent

### ISSUE THREAD

**Issue by piersh** [jzaefferer/jquery-validation#536]
for example, if you tab to an empty, required field you don't trigger an error. however, if you shift-tab (and release both keys) to the field, you'll get an error.

weirder still, if you just tap shift, ctrl, arrow, end, or any other non-printing keys it'll trigger validation.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by piersh** [comment]
Wtf kind of sophmoric project management is this? Yes this bug still exists.
