### ISSUE TITLE
Form submission breaks JQM

### ISSUE THREAD

**Issue by gad2103** [jzaefferer/jquery-validation#540]
the plugin breaks jquery mobile 1.2. when the form submits successfully, the action target of the form is shown, which breaks JQMs default ajax behavior. the html returned upon successful submission should be handled by JQM.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
