### ISSUE TITLE
Inconsistent used of localization

### ISSUE THREAD

**Issue by LaurentGoderre** [jzaefferer/jquery-validation#544]
With regards to Portuguese, there doesn't seem to be a neutral Portuguese, only Brazilian (pt_BR) and Portugal Portuguese (pt_PT). This is inconsistent with the methods Portuguese which is neutral.

It is also inconsistent with other languages that do have a neutral an a locale such as Zhōngwén (zh) and what I assume is Taiwan Zhōngwén (zh_TW).

I would recommend either renaming pt_PT to only pt or create a copy of pt_PT to pt)

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
