### ISSUE TITLE
Error validation issue on select boxes with Android Samsung Galaxy S2

### ISSUE THREAD

**Issue by brainmonger** [jzaefferer/jquery-validation#548]
Hello,

There seems to be an issue when entering valid select box field data on a form after the initial error message displays: 

The issue:
The error message will go away only if you happen to click on the field label text area.

Expected: 
The error message should go away if you click anywhere outside the select box.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
