### ISSUE TITLE
Error messages visibility issue in IE

### ISSUE THREAD

**Issue by mi-k** [jzaefferer/jquery-validation#557]
I am currently using jQuery.validate 1.10.0 with JQuery 1.8.2. I found that on IE validation does work but error labels are empty. In debugger i found that this code was broken:
Line 590:    arguments[i] !== undefined   --> this comparision returns true for undefined element in argument  array and makes my error label text empty. When I use custom message that are called inside defaultMessage function my labels are displayed correctly.

Second problem I found:
Line 603:    !this.settings.ignoreTitle && element.title || undefined   --> returns boolean instead of undefined

I have this issue only on IE (tested on 7,8 and 9), original validate plugin code works fine on Chrome, FF and Opera

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
