### ISSUE TITLE
On keyup, focusout events

### ISSUE THREAD

**Issue by aucman** [jzaefferer/jquery-validation#564]
Hi!

I am just wondering. Is it possible to add a feature to jquery validation plugin where on a particular form you could mark which fileds are validated onkeyup and which onfocusout. So as I am aware now it is only possible to do this for the whole form so you either have a choice to use one or the other but no custumization on particular filed

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
