### ISSUE TITLE
If "remote" endpoint fails, there's no way to rescue

### ISSUE THREAD

**Issue by beatak** [jzaefferer/jquery-validation#565]
because the $.ajax() being called from inside of `$.validator.methods.remote()` does NOT have error handler, if the url failed (404 or whatever), you cannot save the validator at all.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
