### ISSUE TITLE
Cannot add rules to multiple <select> elements at once

### ISSUE THREAD

**Issue by codypearson** [jzaefferer/jquery-validation#570]
Steps to reproduce:

1. Instantiate a validator on an HTML form that includes multiple <select> elements.
2. Write a jQuery selector that selects multiple <select> elements within the same form.
3. Use the jQuery selector to add a new rule to the <select> elements.
4. Trigger a validation on the form.

Expected behavior:
The added validation rule applies to all <select> elements in the collection.

Actual behavior:
The added validation rule only applies to the first <select> element in the collection.

[jsFiddle example](http://jsfiddle.net/Rm3d5/1/)

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
