### ISSUE TITLE
iPad 1 with iOS 5.1.1 refuses validation when a date field is used

### ISSUE THREAD

**Issue by danmiser** [jzaefferer/jquery-validation#571]
I have a small, straight HTML sample available here:
http://www.routexcel.com/jqm

Run this on an iPad 1 with iOS 5.1.1 and press the submit button.
//expected: Continues on to page 2
//actual: Pops up the native datepicker again

I boiled it down to this: This works fine when I leave everything else the same and use jquery.validate 1.8, but it fails starting in 1.9 (and 1.10.0). So the breaking change occurred between 1.8 and 1.9.

If you need something else, please let me know. Thanks!

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
