### ISSUE TITLE
accepted extensions list is working only if required is set to true

### ISSUE THREAD

**Issue by conyg** [jzaefferer/jquery-validation#583]
if you set for example this rule:
    object_picture: {required: false, accept:"jpg|png|gif"}

you get the following error:
   - exception occured when checking element object_picture, check the 'accept' method
   - Uncaught TypeError: Cannot call method 'call' of undefined 
   - TypeError
       arguments: Array[2]
         0: "call"
         1: undefined

No error if required is set to true!

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
