### ISSUE TITLE
TypeError on validation if no validator is defined

### ISSUE THREAD

**Issue by andreaswolf** [jzaefferer/jquery-validation#585]
When calling `valid()` on a form that has no validators attached to any of its elements, there is a "TypeError: validator is undefined". This is because in the `valid()` method, all selected elements are looped, no matter if there really is a validator defined. A simple check `validator !== undefined` around the `each()` call would help.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
