### ISSUE TITLE
issue with twitter bootstrap and jquery validation 

### ISSUE THREAD

**Issue by neilyoung** [jzaefferer/jquery-validation#588]
Error message for file upload is not correctly positioned after validation. I already addressed this to Jasny (creator of the fileupload component) (https://github.com/jasny/bootstrap/issues/51#issuecomment-12248848). His comment was: "Now code is added after input file element, which is incorrect. Please take this up with the guys behind jquery validation." Wha I'm doing by that.

![code1](https://f.cloud.github.com/assets/731020/67333/505c364e-5efa-11e2-8d1a-e21fe8113dbc.PNG)
![code2](https://f.cloud.github.com/assets/731020/67334/5490cd92-5efa-11e2-8f4d-8146060a7fe6.PNG)
![after](https://f.cloud.github.com/assets/731020/67335/57a4f77e-5efa-11e2-8164-ae97e27f3c5f.PNG)

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
