### ISSUE TITLE
Blackberry 10: Dont validate select validation after change

### ISSUE THREAD

**Issue by johanwikstrom** [jzaefferer/jquery-validation#603]
Hi, 

See this simple example.
1. http://jsbin.com/ujixil/2
2. Press submit, you get a validation error 
3. select a value and the error should disapear, but on BB10 it dont. 

Suggestions for workaround or reason for this bug?

/Johan

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
