### ISSUE TITLE
Error Placement is only calling first time

### ISSUE THREAD

**Issue by alvaro-rm** [jzaefferer/jquery-validation#604]
I am using the "errorPlacemen" inside the .validate method but it´s only been called the first time the form has errors.
For example:

Input A has validation errors ---->> I click on Submit -->> errorPlacement is called --->> I correct Input A ---> the error disappears --->> I make another error on Input A ---> the error appears again but errorPlacement IS NOT called !!!

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
