### ISSUE TITLE
Custom validation rules conflicting with HTML5 input type validation rules.

### ISSUE THREAD

**Issue by joshuahiggins** [jzaefferer/jquery-validation#625]
When setting a custom rule on an HTML5 input attribute, both the custom rule and the HTML5 rule are being applied to the input. Should the custom rule not overrule the default rule?

I have put together a [JS Bin demo](http://jsbin.com/onuhen/1/) showcasing this issue. In the example, a custom rule of `data-rule-currency` is applied to an HTML5 input with `type="number"`. 

Although the `data-rule-currency` allows the input number to have a trailing decimal, for example "111.", the `type="number"` rule displays an error. This is buggy behavior and restricts the usage of custom rules in modern HTML5 compliant websites.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
