### ISSUE TITLE
Required with dependency THEN min

### ISSUE THREAD

**Issue by robcurry** [jzaefferer/jquery-validation#633]
Hi,

I might have just overlooked something in the docs but is it possible to have multiple rules, but only if the first rule is matched?

For example, i have a price field, which needs to be validated but ONLY is a specified checkbox is Unticked and also the value must be greater than 0.

I set the "required" and "min" rules but it applies both at the same time. Even in the checkbox is checked, it runs the check for min and causes a validation error.

Is there a way to prevent this, and only run the "min" check if the dependency required is true?

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
