### ISSUE TITLE
BUG in invalidElements()

### ISSUE THREAD

**Issue by darkroastjava** [jzaefferer/jquery-validation#642]
Observed: in version 1.11.0
Strongly resembles https://github.com/jzaefferer/jquery-validation/issues/29 - that bug was closed as a duplicate of 26 which was closed too, but bug 29 still persists!

The validator invalidElements() method seems to return incorrect values in certain cases (and since this is based on the errorList I presume that the errorList is maintained improperly in those cases).

What happens is that if you have a few errors filed and enter a field that is valid, the errors are decremented even if all of the filed errors were from fields other than the one entered.

To reproduce:
1. Open this jsfiddle: http://jsfiddle.net/BJZJJ/3/
    The fiddle has 3 fields. The first and last are required and have intial values. Every time a field is highlighted or unhighlighted the fiddle logs the number of errors to the console.
2. Open the console (e.g. Firebug)
3. Enter the first field and then tab off to activate validation. 0 is logged to the output
5. Go back and remove the value.
6. Tab off again. 1 is logged (correct, since the first required field is now empty).
7. Now enter the 3rd field which is required and has a value.
8. 0 is immediately logged to the output, and the validation error message from the first field disappears.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
