### ISSUE TITLE
issues when used against JQuery 1.9.1

### ISSUE THREAD

**Issue by AnthonyDewhirst** [jzaefferer/jquery-validation#647]
I am testing with IE9 and there is an apparent issue on line 1174.
$.event.handle is 
![validate](https://f.cloud.github.com/assets/642569/182783/2b96f5f6-7c78-11e2-9189-a06386c2e382.png)
![validate2](https://f.cloud.github.com/assets/642569/182786/555bb066-7c78-11e2-8337-d62b55423c59.png)
I did an update with nuget on jquery and have fixed the other issues, just not sure what to do here.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
