### ISSUE TITLE
depends does not work as documented

### ISSUE THREAD

**Issue by DelvarWorld** [jzaefferer/jquery-validation#652]
Based on http://docs.jquery.com/Plugins/Validation/validate#toptions

The language seems to be wrong / very confusing: "Specifies a contact element as required and as email address"

    email: {
        depends: function(element) {
            return $("#contactform_email:checked")
        }
    }

First of all let's point out that this makes 0 sense since the docs tell you to return a jQuery object, not a boolean. Ignoring this, lets try returning a boolean:

`$ cat test.html`

    <html>
    <body>
        <form id="test" action="" method="">
            <input type="checkbox" name="cb" id="cb" />
            <input type="text" name="txt" id="txt" />
        </form>
        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script src="https://raw.github.com/jzaefferer/jquery-validation/master/jquery.validate.js"></script>
        <script>
            $('#test').validate({
                rules: {
                    txt: {
                        depends: function(element) {
                            return $('#cb').is(':checked');
                        }
                    }
                },
                submitHandler: function() {
                    return false;
                }
            });
        </script>
    </body>
    </html>

**To reproduce:**

Type in input box and click away

**Expected result**

Depends function to be called

**Actual result**

`Uncaught TypeError: Cannot call method 'call' of undefined`

Note that changing it to just a collection `$('#cb:checked')` has the same issue. #fixme? or am I just missing something?

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
