### ISSUE TITLE
Using validator.addMethod to extend 'required' throws 'e.validator.methods[o] is undefined' error

### ISSUE THREAD

**Issue by mtnrambler** [jzaefferer/jquery-validation#665]
With the following references:

script src="http://code.jquery.com/jquery-1.9.1.min.js"
script src="http://code.jquery.com/ui/1.10.1/jquery-ui.min.js"
script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/jquery.validate.min.js"

Extending the 'required' validator using this code:

jQuery.validator.methods.oldRequired = jQuery.validator.methods.required; 
jQuery.validator.addMethod("required", function (value, element, param) {
    if (!frm.isNotHint(value, element, param)) { return false; }
    return jQuery.validator.methods.oldRequired.call(this, value, element, param);
},
    jQuery.validator.messages.required
);

Causes the line "return jQuery.validator.methods.oldRequired.call(this, value, element, param);" to throw this error:

TypeError: e.validator.methods[o] is undefined
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/jquery.validate.min.js
Line 4

FYI - The method frm.isNotHint indicates whether the input field contains 'hint' text, and is executed without error.

If the script reference is changed to version 1.10 (http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js), no error is thrown.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by vert5** [comment]
Good call. As the reporter on this (aka, mtnrambler) I've long moved on and could probably not even reproduce it at this point!
