### ISSUE TITLE
shouldn't crash if element isn't found when adding rules

### ISSUE THREAD

**Issue by dimagofman** [jzaefferer/jquery-validation#712]
example code:
```js
$('#txtFirstName',frm).rules('add',{
required: true,
messages: { required: 'First name is required' }
});
```
If the element isn't found, it should be ignored, in the same way as other jquery functions.

exception:
Uncaught TypeError: Cannot read property 'form' of undefined jquery.validate.js:126
$.extend.rules jquery.validate.js:126

Suggested fix:
```js
rules: function( command, argument ) {
var element = this[0];
/* 
check if element is not undefined
e.g. 
if(!element){return this;}
*/
if ( command ) {
...
}
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
