### ISSUE TITLE
jQuery UI dialog incompatible with jquery-validate

### ISSUE THREAD

**Issue by ohcibi** [jzaefferer/jquery-validation#713]
**Demo:  http://jsfiddle.net/ohcibi/YTwFY/2/**

I've included jQuery-ui 1.10.2 manually in this fiddle as jsfiddle doesn't support it yet.

**Steps to reproduce:**

1. Enter some text into the first input field (`name="name"`)
2. Hit the enter key on your keyboard

**Expected:**

* Error is shown as `pinCode` is still empty.
* Form doesn't get submitted
* Dialog gets opened

**What goes wrong:**

* Error is not shown
* Form is submitted

**What goes right:**

* Dialog gets opened

If the first input field is empty **or** the focus is on the second field (`name="pinCode"`) **or** the submit button is clicked, everything is working correctly.

**Workaround:**

Delay the opening of the dialog by 1 ms:

```
invalidHandler: function() {
//...
  setTimeout(function() { 
    $('#dialog-confirm').dialog({
      //...
    });
  }, 1);
//..
}
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
