### ISSUE TITLE
Remote validation calls showErrors before clearing up

### ISSUE THREAD

**Issue by matthewvalimaki** [jzaefferer/jquery-validation#723]
In remote validation we have a success callback and at the very bottom of the callback we have

```javascript
previous.valid = valid;
validator.stopRequest(element, valid);
```

I believe those two lines should go right above

```javascript
if ( valid ) {
...
} else {
...
}
```

Reasoning for this change is the fact, that within if-else clause we call showErrors() while validator.pending still has the element and pending status is > 0. If in showErrors() we want to know before showing errors if the element is still pending remote validation, we will get an incorrect status.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
