### ISSUE TITLE
How to disable/suspend and then re-enable validation

### ISSUE THREAD

**Issue by MartinRobins** [jzaefferer/jquery-validation#725]
I have a form that is used both for the entry of new data and also to view old data.

The rules for entering new data have changed; some of the old data no longer matches the new rules.

I want to be able to suspend validation when in view mode, but restore it when editing. 

Currently, I use `$("#'form").validate().currentForm=""` to disable and `$("#form").validate().currentForm = $("#form")[0]` to reenable - surely there must be a cleaner way?

**Comment by jhyman2** [comment]
If none of the above worked for anyone, I used the following to remove validation on an element when I don't need it.

                $(element).parent().parent().removeClass("has-error");
                $(element).parent().parent().removeClass("has-success");
                $(element).next().remove();

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
