### ISSUE TITLE
Provide AJAX callbacks in remote validation

### ISSUE THREAD

**Issue by pioterj** [jzaefferer/jquery-validation#727]
It would be nice to be able to use callbacks before sending and after completing AJAX request in remote validation. For example this would allow display of a progress indicator. See also forum thread mentioning this at https://groups.google.com/forum/?fromgroups=#!topic/jquery-en/Fv9PEVXzHAY

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
