### ISSUE TITLE
jquerymobile example is broken with jqm 1.3.1

### ISSUE THREAD

**Issue by BilboUK** [jzaefferer/jquery-validation#737]
The example page at http://jquery.bassistance.de/validate/demo/jquerymobile.html is broken with jquery.mobile 1.3.1.  The error text appears *within* the input field. (Because jqm now surrounds the input field in a formatted div.)

A possible solution (attaching the error to the parent element) is suggested here http://www.raymondcamden.com/index.cfm/2012/7/30/Example-of-form-validation-in-a-jQuery-Mobile-Application

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
