### ISSUE TITLE
Bug with fields of "confirmation password" when using multiple forms for validation

### ISSUE THREAD

**Issue by moshkin** [jzaefferer/jquery-validation#738]
My story:

On site I have about 4-5 similar forms to validate, I created similar rules for them.

Because i didn't want copy identical code 4-5 times and customize settings this "rule" for each form. When I added validate field "password and confirm password" I do it like this
```js
password: {
	required : true,
	minlength: 8
},
passwordConfirm: {
	equalTo : ".password",
	required : true,
	minlength: 8
} 
```
I added to equalTo : ".password", class because 4-5 form can't contain each unique element "#password" into each form on document. 

When I checked all forms, I seen what only first form worked, because function equalTo finded all elements ".password" on document.
```js
var target = $(param) 
```
and then compared value === target.val() 
variable targeе -> contained all my ".password" elements on my document and target.val() got value for first element in array of elements :(

I fixed it similar this
```js
var target = $(param, this.currentForm);
```
Maybe not elegant method but it works.
```js
equalTo: function( value, element, param ) {
	// bind to the blur event of the target in order to revalidate whenever the target field is updated
	// TODO find a way to bind the event just once, avoiding the unbind-rebind overhead
	var target = $(param, this.currentForm);
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
