### ISSUE TITLE
Remote validation bug

### ISSUE THREAD

**Issue by lrscj** [jzaefferer/jquery-validation#751]
Remote field validation works badly. It validates the field, but it removes invalid class from the other fields (local fields).
The bug comes from showErrors function. There is there 
```js
            for ( var name in errors  ) { 
```
But it should be
```js
            for ( var name in this.errorMap ) { 
```
because invalid fields should be still invalid after remove validation.
Thanks.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
