### ISSUE TITLE
additional methods - IIFE

### ISSUE THREAD

**Issue by iamandycohen** [jzaefferer/jquery-validation#759]
Curious as to why the top of the additional methods script has an IIFE (immediately invoked function expression) which wraps a few of the additional methods, but not the rest.  Why not just wrap the whole script with the IIFE, but pass it jQuery as a $ parameter:
```js
(function($) {

//// code omitted for brevity

})(jQuery);
```
This would get rid of the problem that I previously submitted a pull request for (which was accepted).

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
