### ISSUE TITLE
cannot update invalidHandler after initialization

### ISSUE THREAD

**Issue by iamandycohen** [jzaefferer/jquery-validation#765]
If you update the invalidHandler after initialization, the original event handler will always fire.  This is because of the way that invalidHandler is set up.

This is in jquery.validate:
```js
			if ( this.settings.invalidHandler ) {
				$(this.currentForm).bind("invalid-form.validate", this.settings.invalidHandler);
			}
```
The way around this is to update the event handler:
```js
            $form.off('invalid-form.validate')
                .on('invalid-form.validate', newInvalidHandler);
```

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by KyleMit** [comment]
See also this Stack Overflow Question: [How to add a 'submitHandler' function when using jQuery Unobtrusive Validation?](https://stackoverflow.com/q/4747017/1366033) which has the same solution as [iamandycohen](https://github.com/jquery-validation/jquery-validation/issues/765#issuecomment-18866506):

```js
$("form").bind("invalid-form.validate", function () {
  alert('invalid!');
});
```
