### ISSUE TITLE
BIC validator

### ISSUE THREAD

**Issue by toabi** [jzaefferer/jquery-validation#770]
It's about this code/regex: https://github.com/jzaefferer/jquery-validation/blob/master/additional-methods.js#L279-L294

Is nice and complies to what is written on Wikipedia. BUT: I encountered BICs like for example `ESSLDE66XXX`. This doesn't match the regular expression.

Sadly I do not have access to ISO 9362:2009 to see what exactly is going on there.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by BeOleg** [comment]
code moved here:
https://github.com/jquery-validation/jquery-validation/blob/bb0c335c7ad44765569426d60977cdf5666849cb/src/additional/bic.js

pretty comprehensive I<HO
