### ISSUE TITLE
Nested cross origin iframe generates permission denied error in IE

### ISSUE THREAD

**Issue by jedatu** [jzaefferer/jquery-validation#777]
Given the following conditions:

A form has a nested iframe that is determined by the browser to be cross origin.

```html
<form>
    <iframe src="http://cross-domain/site/url" />
</form>
```

The following code will throw a permission denied error:

```javascript
validateDelegate: function( delegate, type, handler ) {
			return this.bind(type, function( event ) {
				var target = $(event.target);
				if ( target.is(delegate) ) {
					return handler.apply(target, arguments);
				}
			});
		}
```

The `if (target.is(delegate))` evaluation will fail in IE and possibly other browsers because the parent page does not have access to the "type" property of the iframe.

For instance, 
* An event listener is attached to the form listening for "focusin, focusout, keyup'
* The focus turns to the iframe which triggers the event
* The bound function tries to evaluate the type to determine whether the target should be validated
* The type information is inaccessible
* The permission denied error is thrown

I suppose this could be considered a jQuery bug as well.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
