### ISSUE TITLE
Character unmasking on Windows handsets when generating client-side error.

### ISSUE THREAD

**Issue by jaffnae** [jzaefferer/jquery-validation#779]
There's an issue on the Windows mobile browser where if a client-side error is generated against a Password field (input type="password") the masking behaviour is altered.

By default when typing the password the last character is unmasked. When using jQuery Validate, after an error is generated no character is unmasked at all.

When using jQuery Validate in conjunction with jQuery Unobtrusive Validate the first character is unmasked when typing  instead of the last one.

Here's a jsfiddle of this issue: http://jsfiddle.net/4vjpr/2/ 

Please view on a Windows Phone (tested on Nokia Lumia 920 and HTC Windows Phone 8X)

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
