### ISSUE TITLE
remote check if same value before updating message

### ISSUE THREAD

**Issue by kinergy** [jzaefferer/jquery-validation#809]
Hi, I have a user profile form which uses a remote validation server call to validate whether the email address is already taken. The problem I'm trying to solve is if the user doesn't edit the email address, during validation the email address is validated as taken already (I don't pass to the server who is asking, the server just responds that somebody has used that email address).

The solution I have found is to apply this to my view just after it is rendered:

````javascript
var $email = $("input[name='email']");
$email.data('previousValue', {old: $email.val(), valid: true });
````

This works since I know that the original value is valid to begin with. The only problem is that I had to make the following change to jquery.validate.js so that on the first validation pass for the email field, the custom message is not mangled since `previous.message` is `undefined`.

````javascript
remote: function( value, element, param ) {
	if ( this.optional(element) ) {
		return "dependency-mismatch";
	}

	var previous = this.previousValue(element);

	// **** Moved from below:
	if ( previous.old === value ) {
		return previous.valid;
	}

	if (!this.settings.messages[element.name] ) {
		this.settings.messages[element.name] = {};
	}
	previous.originalMessage = this.settings.messages[element.name].remote;
	this.settings.messages[element.name].remote = previous.message;

	param = typeof param === "string" && {url:param} || param;

	// if ( previous.old === value ) {
	// 	return previous.valid;
	// }
````
I call `$elem.valid()` for each form input as I decide whether to save it automatically, and if jquery.validate.js has a provision to ignore fields that haven't changed, this may be overriding it.

Alternatively, I could specify `previousValue.message = <my message for email taken goes here>`, however ideally I'd avoid specifying that twice.

I'm wondering which is the better solution: (1) if there is a better solution to my problem so that the `remote` on my email input isn't called unless the value actually changes, or (2) I just redundantly specify `previousValue.message`, or (3) you'd accept a pull request to make this change.

thanks!

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!
